module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  rootDir: '.',
  roots: ['<rootDir>/../tests/unit'],
  setupFiles: ['<rootDir>/../tests/unit/setup/env.ts'],
  testPathIgnorePatterns: ['/node_modules/', 'chat-mini.utils.test.ts'],
  testMatch: ['**/*.test.ts'],
  clearMocks: true,
  restoreMocks: true,
  testTimeout: 30000,
  modulePaths: ['<rootDir>/node_modules'],
  moduleFileExtensions: ['ts', 'js', 'json'],
  transform: {
    '^.+\\.ts$': ['ts-jest', { tsconfig: '<rootDir>/tsconfig.jest.json', isolatedModules: true }],
  },
  collectCoverage: true,
  coverageDirectory: 'coverage',
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/server.ts',
    '!src/test.ts',
    '!src/**/*.d.ts',
  ],
  coverageReporters: ['text', 'lcov', 'html'],
};
